---
- name: install build requirements
  become: true
  apt:
    name:
      - libmicrohttpd-dev
      - libjansson-dev
      - libssl-dev
      - libsrtp2-dev
      - libsofia-sip-ua-dev
      - libglib2.0-dev
      - libopus-dev
      - libogg-dev
      - libcurl4-openssl-dev
      - liblua5.3-dev
      - libconfig-dev
      - libnice-dev
      - pkg-config
      - gengetopt
      - libtool
      - automake

- name: clone
  become: false
  git:
    repo: https://github.com/meetecho/janus-gateway
    dest: "{{ janus_home }}"
    update: true
    version: "{{ janus_version }}"
- name: autogen
  become: false
  shell:
    chdir: "{{ janus_home }}"
    cmd: ./autogen.sh
- name: build
  become: false
  shell:
    chdir: "{{ janus_home }}"
    cmd: |
      ./configure --prefix=/opt/janus
      make
- name: janus directory
  become: true
  file:
    path: /opt/janus
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
- name: install
  become: false
  shell:
    chdir: "{{ janus_home }}"
    cmd: make install
- name: check configuration
  stat:
    path: /opt/janus/etc/janus
  register: config_dir_check
- name: initiate configuration
  shell:
    chdir: "{{ janus_home }}"
    cmd: make configs
  when:
    - not config_dir_check
