---
- name: install build requirements
  apt:
    name:
      - libmicrohttpd-dev
      - libjansson-dev
      - libssl-dev
      - libsrtp2-dev
      - libsofia-sip-ua-dev
      - libglib2.0-dev
      - libopus-dev
      - libogg-dev
      - libcurl4-openssl-dev
      - liblua5.3-dev
      - libconfig-dev
      - libnice-dev
      - pkg-config
      - gengetopt
      - libtool
      - automake
      - build-essential

- name: clone
  git:
    repo: https://github.com/meetecho/janus-gateway
    dest: "{{ janus_src }}"
    update: false
    version: "{{ janus_version }}"
- name: autogen
  command: ./autogen.sh
  args:
    chdir: "{{ janus_src }}"
    creates: m4
- name: configure
  command: ./configure --prefix={{ janus_home }}
  args:
    creates: Makefile
    chdir: "{{ janus_src }}"
- name: build
  command: make
  args:
    chdir: "{{ janus_src }}"
    creates: janus
- name: janus directory
  file:
    path: /opt/janus
    mode: 0755
    state: directory
- name: install
  command: make install
  args:
    chdir: "{{ janus_src }}"
    creates: "{{ janus_home }}/bin/janus"

- name: configuration
  template:
    mode: 0644
    src: "{{ item }}.j2"
    dest: "{{ janus_home }}/etc/janus/{{ item }}"
  loop:
    - janus.eventhandler.gelfevh.jcfg
    - janus.eventhandler.sampleevh.jcfg
    - janus.jcfg
    - janus.plugin.audiobridge.jcfg
    - janus.plugin.echotest.jcfg
    - janus.plugin.nosip.jcfg
    - janus.plugin.recordplay.jcfg
    - janus.plugin.sip.jcfg
    - janus.plugin.streaming.jcfg
    - janus.plugin.textroom.jcfg
    - janus.plugin.videocall.jcfg
    - janus.plugin.videoroom.jcfg
    - janus.plugin.voicemail.jcfg
    - janus.transport.http.jcfg
    - janus.transport.pfunix.jcfg
